In [1]:
def bench():
    start=time.time()
    for e in range(10000):
        n=n@n

In [2]:
def bench():
    start=time.time()
    n = np.random.rand(8,8,12,12)
    for e in range(10000):
        n=n@n

In [3]:
def bench(i):
    start=time.time()
    n = np.random.rand(8,8,12,12,dtype=np.uint8)
    for e in range(i):
        n=n@n
    end=time.time()
    return end - start


In [4]:
bench(10)

NameError: name 'time' is not defined

In [5]:

import numpy as np ; import time

In [6]:
bench(10)

TypeError: rand() got an unexpected keyword argument 'dtype'

In [7]:
def bench(i):
    start=time.time()
    n = np.random.rand(8,8,12,12).astype("uint8")
    for e in range(i):
        n=n@n
    end=time.time()
    return end - start


In [8]:
bench(10)

0.004060983657836914

In [9]:
bench(10000)

0.9129230976104736

In [10]:
n

NameError: name 'n' is not defined

In [11]:
def bench(i):
    start=time.time()
    n = np.random.rand(8,8,12,12).astype("uint8")
    for e in range(i):
        n=n@n
    end=time.time()
    return end - start, n


In [12]:
t,n=bench(10000)

In [13]:
t

0.8930618762969971

In [14]:
n

array([[[[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],

        [[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],

        [[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],

        ...,

        [[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],

        [[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
    

In [15]:
def bench(i):
    start=time.time()
    a = np.random.rand(8,8,12,12).astype("uint8")
    b = np.random.rand(8,8,12,12).astype("uint8")
    for e in range(i):
        n=a@b
    end=time.time()
    return end - start, n


In [16]:
t,n=bench(10000)

In [17]:
t

0.9262034893035889

In [18]:
n

array([[[[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],

        [[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],

        [[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],

        ...,

        [[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],

        [[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
    

In [19]:
def bench(i):
    start=time.time()
    a = np.random.randint(0,255,(8,8,12,12),np.uint8).astype("uint8")
    b = np.random.randint(0, 255, (8,8,12,12),np.uint8).astype("uint8")
    for e in range(i):
        n=a@b
    end=time.time()
    return end - start, n


In [20]:
t,n=bench(10000)

In [21]:
n

array([[[[ 81,  84,   2, ...,  22, 250, 206],
         [ 54, 251, 196, ..., 217, 194,  98],
         [ 96,  55,  41, ...,  46,  68, 233],
         ...,
         [ 63, 124, 195, ...,  42, 169, 131],
         [ 71, 220,  20, ..., 206,  38,  11],
         [146, 211, 229, ...,  58, 182, 143]],

        [[ 29,  72, 170, ..., 247, 119,  52],
         [161,  35,  24, ..., 243,  54,  69],
         [192, 127, 120, ...,  49,  54,   4],
         ...,
         [ 53,  28, 102, ...,  28, 159,  72],
         [ 62, 218,  50, ...,  38,  25,  80],
         [200,  61,  34, ...,  21,  22, 214]],

        [[247,   5, 236, ..., 234, 148, 103],
         [ 23, 215, 238, ..., 246,  53, 189],
         [ 53, 100, 187, ...,  86,  44,  40],
         ...,
         [119,  79,  47, ..., 135, 165, 165],
         [250, 118, 235, ..., 161, 197, 143],
         [ 73, 108, 180, ...,  20, 101, 232]],

        ...,

        [[206, 137, 107, ..., 206,  59,  82],
         [ 51,  44, 120, ..., 116,   1, 180],
         [ 51, 182

In [22]:
t

0.9310786724090576

In [23]:
6*16

96

In [24]:
1ms en theorie

SyntaxError: invalid syntax (<ipython-input-24-d48ef6ca055a>, line 1)